os: Visual Studio 2017

platform: x64

branches:
  only:
    - master
    
clone_folder: c:\gopath\src\github.com\shiyuli\ChangeAssemblyInfo

version: "{branch}.{build}"

environment:
  GOPATH: c:\gopath

stack: go 1.10

build_script:
  - go build -o ./bin/ChangeAssemblyInfo.exe ./src/main.go

artifacts:
  - path: ./bin/ChangeAssemblyInfo.exe
    name: release

test_script:
  - cd bin
  - ChangeAssemblyInfo.exe ./AssemblyInfo.cs
